/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_END = "AUTH_LOGIN_END";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";
export const AUTH_LOGOUT_END = "AUTH_LOGOUT_END";

export const AUTH_LOGGED_IN = "AUTH_LOGGED_IN";

/* REGISTER */

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_END = "SIGNUP_END";

/* MEETING */

export const CREATE_MEETING = "CREATE_MEETING";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILURE = "CREATE_MEETING_FAILURE";
export const CREATE_MEETING_END = "CREATE_MEETING_END";

export const MEETING_STATUS_END = "MEETING_STATUS_END";
export const MEETING_STATUS_WAIT = "MEETING_STATUS_WAIT";

export const MEETING_LIST_LOAD = "MEETING_LIST_LOAD";
export const MEETING_LIST_LOAD_SUCCESS = "MEETING_LIST_LOAD_SUCCESS";
export const MEETING_LIST_LOAD_FAILURE = "MEETING_LIST_LOAD_FAILURE";
export const MEETING_LIST_LOAD_END = "MEETING_LIST_LOAD_END";

export const MEETING_LOAD = "MEETING_LOAD";
export const MEETING_LOAD_SUCCESS = "MEETING_LOAD_SUCCESS";
export const MEETING_LOAD_FAILURE = "MEETING_LOAD_FAILURE";
export const MEETING_LOAD_END = "MEETING_LOAD_END";

export const MEETING_SAVE = "MEETING_SAVE";
export const MEETING_SAVE_SUCCESS = "MEETING_SAVE_SUCCESS";
export const MEETING_SAVE_FAILURE = "MEETING_SAVE_FAILURE";
export const MEETING_SAVE_END = "MEETING_SAVE_END";
